name: FileWebserver
services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PORT=${PORT:-1000}
    ports:
      - "${PORT:-1000}:${PORT:-1000}"
    volumes:
      - "${HOST_PUBLISHED_FOLDER:-/Users/rodolphe/Public/}:/app"
